AWSTemplateFormatVersion: '2010-09-09'
Description: TP4 INF8102 - Secure S3 Bucket polystudens3 with KMS, Versioning, Replication, and CloudTrail
Outputs:
  S3BucketArn:
    Description: ARN of the secure S3 bucket.
    Value: !Join
      - ''
      - - 'arn:aws:s3:::'
        - !Ref 'PolystudentS3Bucket'
  S3ReplicaBucketArn:
    Description: ARN of the replica S3 bucket.
    Value: !Join
      - ''
      - - 'arn:aws:s3:::'
        - !Ref 'PolystudentS3ReplicaBucket'
Resources:
  PolystudentS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: polystudens3-596556162691
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: arn:aws:kms:us-east-1:596556162691:key/c41c9b30-c57e-424d-aa3b-634e00109bd8
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: arn:aws:iam::596556162691:role/LabRole
        Rules:
          - Id: FullReplication
            Priority: 1
            Status: Enabled
            Filter:
              Prefix: ''
            DeleteMarkerReplication:
              Status: Disabled
            Destination:
              Bucket: !GetAtt 'PolystudentS3ReplicaBucket.Arn'
              EncryptionConfiguration:
                ReplicaKmsKeyID: arn:aws:kms:us-east-1:596556162691:key/c41c9b30-c57e-424d-aa3b-634e00109bd8
            SourceSelectionCriteria:
              SseKmsEncryptedObjects:
                Status: Enabled
      Tags:
        - Key: Name
          Value: polystudens3-596556162691
  PolystudentS3ReplicaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: polystudents3-back-596556162691
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: polystudents3-back-596556162691
  
  # NEW RESOURCE: Bucket Policy to allow CloudTrail to write logs
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PolystudentS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt 'PolystudentS3Bucket.Arn'
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Join 
              - ''
              - - !GetAtt 'PolystudentS3Bucket.Arn'
                - '/AWSLogs/'
                - !Ref 'AWS::AccountId'
                - '/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  S3ObjectAccessTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: S3BucketPolicy
    Properties:
      S3BucketName: !Ref 'PolystudentS3Bucket'
      IsLogging: true
      IsMultiRegionTrail: false
      IncludeGlobalServiceEvents: false
      EventSelectors:
        - DataResources:
            - Type: AWS::S3::Object
              Values:
                - !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - polystudens3-596556162691
                    - /
          IncludeManagementEvents: false
          ReadWriteType: All
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - polystudentlab
              - s3-cloudtrail